import type { ReactNode } from "react";

interface AiModelsLayoutProps {
  children: ReactNode;
}

const mobileFixClasses = [
  "[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400]:py-6",
  "md:[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400]:py-8",
  "[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child]:mb-6",
  "[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child]:gap-3",
  "md:[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child]:mb-8",
  "md:[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child]:gap-4",
  "[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child>div:last-child]:w-full",
  "md:[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child>div:last-child]:w-auto",
  "[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child>div:last-child>div]:w-full",
  "[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child>div:last-child>div]:gap-2",
  "md:[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child>div:last-child>div]:w-auto",
  "md:[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child>div:last-child>div]:gap-3",
  "[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child>div:last-child_a]:w-full",
  "[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child>div:last-child_a]:justify-center",
  "[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child>div:last-child_button]:w-full",
  "[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child>div:last-child_button]:justify-center",
  "md:[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child>div:last-child_a]:w-auto",
  "md:[&_main.min-h-screen.bg-linear-to-br.from-slate-50.to-slate-100>div.mx-auto.max-w-400>div:first-child>div:last-child_button]:w-auto",
  "[&_section.p-0_.border-slate-200.border-b>div]:flex-col",
  "[&_section.p-0_.border-slate-200.border-b>div]:items-stretch",
  "[&_section.p-0_.border-slate-200.border-b>div]:gap-3",
  "md:[&_section.p-0_.border-slate-200.border-b>div]:flex-row",
  "md:[&_section.p-0_.border-slate-200.border-b>div]:items-start",
  "md:[&_section.p-0_.border-slate-200.border-b>div]:justify-between",
  "[&_section.p-0_.border-slate-200.border-b>div>.rounded-xl]:text-left",
  "md:[&_section.p-0_.border-slate-200.border-b>div>.rounded-xl]:text-right",
  "[&_section.p-0_.overflow-x-auto]:overflow-x-visible",
  "md:[&_section.p-0_.overflow-x-auto]:overflow-x-auto",
  "[&_section.p-0_table.min-w-full]:min-w-0",
  "[&_section.p-0_table.min-w-full]:w-full",
  "[&_section.p-0_table.min-w-full]:table-fixed",
  "md:[&_section.p-0_table.min-w-full]:min-w-full",
  "md:[&_section.p-0_table.min-w-full]:table-auto",
  "[&_section.p-0_table.min-w-full_thead]:hidden",
  "md:[&_section.p-0_table.min-w-full_thead]:table-header-group",
  "[&_section.p-0_table.min-w-full_tbody]:grid",
  "[&_section.p-0_table.min-w-full_tbody]:gap-3",
  "[&_section.p-0_table.min-w-full_tbody]:p-4",
  "md:[&_section.p-0_table.min-w-full_tbody]:table-row-group",
  "md:[&_section.p-0_table.min-w-full_tbody]:gap-0",
  "md:[&_section.p-0_table.min-w-full_tbody]:p-0",
  "[&_section.p-0_table.min-w-full_tr]:block",
  "[&_section.p-0_table.min-w-full_tr]:overflow-hidden",
  "[&_section.p-0_table.min-w-full_tr]:rounded-2xl",
  "[&_section.p-0_table.min-w-full_tr]:border",
  "[&_section.p-0_table.min-w-full_tr]:border-slate-200",
  "[&_section.p-0_table.min-w-full_tr]:bg-white",
  "md:[&_section.p-0_table.min-w-full_tr]:table-row",
  "md:[&_section.p-0_table.min-w-full_tr]:overflow-visible",
  "md:[&_section.p-0_table.min-w-full_tr]:rounded-none",
  "md:[&_section.p-0_table.min-w-full_tr]:border-0",
  "md:[&_section.p-0_table.min-w-full_tr]:bg-transparent",
  "[&_section.p-0_table.min-w-full_td]:block",
  "[&_section.p-0_table.min-w-full_td]:w-full",
  "[&_section.p-0_table.min-w-full_td]:px-4",
  "[&_section.p-0_table.min-w-full_td]:py-3",
  "[&_section.p-0_table.min-w-full_td]:text-left",
  "[&_section.p-0_table.min-w-full_td]:whitespace-normal",
  "md:[&_section.p-0_table.min-w-full_td]:table-cell",
  "md:[&_section.p-0_table.min-w-full_td]:w-auto",
  "md:[&_section.p-0_table.min-w-full_td]:px-4",
  "md:[&_section.p-0_table.min-w-full_td]:py-4",
  "[&_section.p-0_table.min-w-full_td:nth-child(2)]:break-all",
  "md:[&_section.p-0_table.min-w-full_td:nth-child(2)]:break-normal",
  "[&_section.p-0_table.min-w-full_td:last-child]:flex",
  "[&_section.p-0_table.min-w-full_td:last-child]:items-center",
  "[&_section.p-0_table.min-w-full_td:last-child]:justify-end",
  "md:[&_section.p-0_table.min-w-full_td:last-child]:table-cell",
].join(" ");

export default function AiModelsLayout({ children }: AiModelsLayoutProps) {
  return <div className={mobileFixClasses}>{children}</div>;
}
